function EEG = notch(EEG)
%NOTCH Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 25.1 and DSP System Toolbox 25.1.
% Generated on: 11-Sep-2026 12:49:43

% IIR Notching filter designed using the IIRNOTCH function.

% All frequency values are in Hz.
Fs = EEG.srate;  % Sampling Frequency

Fnotch = 50;  % Notch Frequency
BW     = 2;   % Bandwidth
Apass  = 1;   % Bandwidth Attenuation

[b, a] = iirnotch(Fnotch/(Fs/2), BW/(Fs/2), Apass);
Hd     = dfilt.df2(b, a);
eeg_filt_ranura=zeros(size(EEG.data));
for i=1:EEG.nbchan
    % eeg_filt_ranura(i,:)=filter(num_ranura,den_ranura,double(eeg_filt_lp(i,:)));
    eeg_filt_ranura(i,:)=filter(Hd,double(EEG.data(i,:)));
end
figure(4)
periodogram(eeg_filt_ranura(1,:),[],1024,256)
hold on;
periodogram(EEG.data(1,:),[],1024,256)
EEG.data=eeg_filt_ranura;
EEG=eeg_checkset(EEG);
% [EOF]
