function Hd = notch100
%NOTCH100 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 25.1 and DSP System Toolbox 25.1.
% Generated on: 11-Sep-2026 16:13:37

% IIR Notching filter designed using the IIRNOTCH function.

% All frequency values are in Hz.
Fs = 256;  % Sampling Frequency

Fnotch = 100;  % Notch Frequency
BW     = 1;    % Bandwidth
Apass  = 1;    % Bandwidth Attenuation

[b, a] = iirnotch(Fnotch/(Fs/2), BW/(Fs/2), Apass);
Hd     = dfilt.df2(b, a);

% [EOF]
