function EEG = pasaalto(EEG)
%PASAALTO Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 25.1 and DSP System Toolbox 25.1.
% Generated on: 14-Sep-2026 21:21:47

% Butterworth Highpass filter designed using FDESIGN.HIGHPASS.

% All frequency values are in Hz.
%Fs = 256;  % Sampling Frequency
Fs=EEG.srate;
N  = 4;    % Order
Fc = 3.5;  % Cutoff Frequency
eeg_filt_hp=zeros(size(EEG.data));
% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.highpass('N,F3dB', N, Fc, Fs);
Hd = design(h, 'butter');
for i=1:EEG.nbchan
    eeg_filt_hp(i,:)=filter(Hd,double(EEG.data(i,:))); 
end
% [EOF]
%figure()
periodogram(EEG.data(5,:),[],1024,256)
 hold on;
periodogram(eeg_filt_hp(5,:),[],1024,256)
EEG.data=eeg_filt_hp;
EEG=eeg_checkset(EEG);
