function EEG = pasabajo(EEG)
%PASABAJO Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 25.1 and DSP System Toolbox 25.1.
% Generated on: 14-Sep-2026 21:30:01

% Butterworth Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are in Hz.
Fs = EEG.srate;  % Sampling Frequency
eeg_filt_lp=zeros(size(EEG.data));
N  = 4;   % Order
Fc = 90;  % Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.lowpass('N,F3dB', N, Fc, Fs);
Hd = design(h, 'butter');
for i=1:EEG.nbchan
    eeg_filt_lp(i,:)=filter(Hd,double(EEG.data(i,:)));
end
figure(3);
periodogram(EEG.data(5,:),[],1024,256)
hold on;
periodogram(eeg_filt_lp(5,:),[],1024,256)
EEG.data=eeg_filt_lp;
EEG=eeg_checkset(EEG);

% [EOF]
